### ISSUE TITLE
Content area renderer conflict

### ISSUE THREAD

**Issue by TNMH** [advanced-cms/advanced-reviews#103] opened 2020-02-04 10:46 UTC
Hi,

Upon installing the advanced review plugin, we noticed some custom functionality of ours break.
Upon further inspection, the custom content area renderer we are using to provide some functionality is being overwritten by your custom implementation.

The issue is that you are registering your custom implementation using an intercept method, which is depriving us of our own implementation.

The problem lies in the following code:
`context.Services.Intercept<ContentAreaRenderer>((Func<IServiceLocator, ContentAreaRenderer, ContentAreaRenderer>) ((locator, defaultContentAreaRenderer) => (ContentAreaRenderer) new DraftContentAreaRenderer(defaultContentAreaRenderer)));`

We are using this implementation to add display options to our content items; something that happens in the Alloy project as well. As a consequence, we have to choose between the two functionalities.

The solution we're proposing is the following:
By adding your DraftContentAreaRenderer to the container, we'd be able to choose which content area renderer to use by overwriting the following class:

`public static class ContentAreaExtensions
  {
    /// <summary>Renders the content area on the stream.</summary>
    /// <param name="htmlHelper">The HTML.</param>
    /// <param name="contentArea">The content area.</param>
    public static void RenderContentArea(this HtmlHelper htmlHelper, ContentArea contentArea)
    {
      ServiceLocator.Current.GetInstance<ContentAreaRenderer>().Render(htmlHelper, contentArea);
    }
  }`

Here, we'd be able to check, depending on the context, which content area renderer to use.

We can only do so, however, if you add your renderer to the container instead of overwriting all implementations. For further information, you can view the AlloyContentAreaRenderer in the Alloy project, which we've based our implementation on.

Sincerely,
Tim

**Comment by barteksekula** [comment] 2020-02-08 17:34
@TNMH 
We have this call:
https://github.com/advanced-cms/advanced-reviews/blob/master/src/external-reviews/DraftContentAreaPreview/DraftContentAreaRenderer.cs#L60

It calls the orignal RenderContentAreaItems from the instance registered in the container.

Maybe it's just the matter of order in your scenario? Have you tried also intercepting ContentAreaLoader?

Are you able to reproduce your issue in the Alloy demo site from this repository?

It was very tricky for us to write that DraftContentAreaRenderer so the more info you give us (or ideally a fork with a failing scenario) the faster we will be able to help you.

Thanks!

**Comment by argetgarzjla** [comment] 2020-02-10 10:57
@barteksekula 
The call will not help us in this case. The issue is that even if you call the original instance, because your content area renderer is being registered via an intercept, the default implementation and our custom implementation is overwritten by yours. You can see this in the screenshot underneath:

![image](https://user-images.githubusercontent.com/25726984/74143651-78931100-4bfb-11ea-8a0f-221aa8992d18.png)

As you can see, we have registered an additional content area renderer next to the default one. When the IoC registration is finished however, your intercept will override both implementations, meaning we have neither the default nor our own implementation registered. 

We're not asking you to rewrite the DraftContentAreaRenderer, just to register it in a different way,
so it doesn't overwrite our implementation.

Kind regards,
Arne

**Comment by barteksekula** [comment] 2020-02-14 06:47
Could you please check if this renderer works for you?
https://github.com/advanced-cms/advanced-reviews/blob/master/src/alloy/Business/Rendering/AlloyContentAreaRenderer.cs
This is the sample custom renderer in Alloy and it seems to work just fine with DraftContentAreaRenderer.
In the end it's only 1 ContentAreaRenderer that is used by the IoC container so it does not matter how many or how are registered.
Have you tried also injecting your custom stuff as intercept which is executed in a module with dependency set to our module from this package? so that yours would decorate ours?

You could also share your renderer here (or if you prefer just shoot me an private message) so that we can reproduce your issue.

**Comment by barteksekula** [comment] 2020-03-05 08:51
@TNMH @argetgarzjla we have some time today so we can try to help you with this one. Are you still interested?

**Comment by argetgarzjla** [comment] 2020-06-05 08:15
Hi,

due to shifting priorities, we weren't able to follow this up immediately,
In the meantime, we have found a workaround and have implemented the system.

Thank you for your time. You can close this question now,
Sincerely,
Arne

**Comment by barteksekula** [comment] 2020-06-05 10:04
@argetgarzjla could you please share the workaround?

**Closed** 2020-06-08 15:58 UTC
