### ISSUE TITLE
Console error on sharing of links

### ISSUE THREAD

**Issue by baier** [advanced-cms/advanced-reviews#106] opened 2020-02-05 11:42 UTC
It is possible to create a view link and a edit link, but sharing the link through the share-dialog gives a console error: 

![image](https://user-images.githubusercontent.com/1081200/73838865-f24e8780-4814-11ea-9ba0-e33dca24a962.png)

Use the following code to do an initialization:
```
    [InitializableModule]
    [ModuleDependency(typeof(FrameworkInitialization))]
    public class ExternalReviewInitialization : IConfigurableModule
    {
        public void ConfigureContainer(ServiceConfigurationContext context)
        {
            context.Services.Configure<ExternalReviewOptions>(options =>
            {
                options.EditableLinksEnabled = true;
                options.IsEnabled = true;
            });
        }

        public void Initialize(InitializationEngine context) { }

        public void Uninitialize(InitializationEngine context) { }
    }
```
Version is 0.5.2.

**Comment by baier** [comment] 2020-02-05 11:55
We use Azure AD for authentication, if that's relevant.

**Comment by matkun** [comment] 2020-02-05 12:13
The exception seems to be thrown when NotificationEmailAddress is not set on Episerver's notification options
```
if (string.IsNullOrWhiteSpace(_notificationOptions.NotificationEmailAddress))
{
   return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Sender email address is not configured. Contact with system administrator");
}
```
If I remember correctly this is populated from the configuration file at _system.net/mailSettings/smtp_ (the from-attribute).

```
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="Network" from="noreply@foo.se">
        <network host="mailrelay.foo.se" port="25" defaultCredentials="true" />
      </smtp>
    </mailSettings>
  </system.net>
```

Hope it helps

**Comment by baier** [comment] 2020-02-05 12:54
I've tested with both the snippet you've written above and setting this:
`  <applicationSettings defaultNotificationEmailAddress="notifications@example.com" defaultNotificationEmailDisplayName="Episerver" />`

They both remove the console error, but no email is sent.

**Comment by matkun** [comment] 2020-02-05 13:04
Perhaps trying a pickup directory could help you determine if the problem is code related or has to do with the mail server or connection to it.

You could try to keep the defaultNotificationEmailAddress and configure something like below

```
<configuration>  
  <system.net>  
    <mailSettings>  
      <smtp deliveryMethod="SpecifiedPickupDirectory">  
        <specifiedPickupDirectory  
          pickupDirectoryLocation="c:\maildrop"  
        />  
      </smtp>  
    </mailSettings>  
  </system.net>  
</configuration>
```

**Comment by baier** [comment] 2020-02-05 13:52
The are indeed generated email-files i c:\maildrop when we trigger the link sharing, but I think it is odd that we would need to specify a mailserver for this now, as we've never had an email server on the solution before (and it has worked before). Could it have something to do with the authentication? Apparently my user in Azure AD isn't associated with an email address, which seems to be the parameter missing. I might add we've probably worked with an earlier version of the Advanced Review Add-on when it _did_ work, too.

**Comment by barteksekula** [comment] 2020-02-06 09:31
@baier @matkun we use the built-in EmailNotificationProvider
https://github.com/advanced-cms/advanced-reviews/blob/master/src/external-reviews/ReviewLinksRepository/ExternalReviewStore.cs#L149

which as you found out uses those config options:
`
<applicationSettings defaultNotificationEmailAddress=”notifications@example.com” 
                     defaultNotificationEmailDisplayName=”Episerver” >
`
https://world.episerver.com/documentation/developer-guides/CMS/Deployment/configuring-your-email-server/

I will have to test it myself to know what's wrong.
Will get back to you

**Comment by jtonvang** [comment] 2020-02-07 12:00
We're having the same issue - using the SMTP-server provided by Episerver as part of the DXC-service. 
The logs indicate that the problem is that the certificate of the SMTP server cannot be validated. 
We've fixed this in our own email service by overriding this in the certificate validation callback - if you'd like I can submit a PR with this fix.

**Comment by barteksekula** [comment] 2020-02-08 14:57
@jtonvang does the SMTP work for regular epi notifications and only fail for reviews? please create a PR if you have a fix. we will appreciate all contributions! :)

**Comment by jtonvang** [comment] 2020-02-10 09:04
@barteksekula No, the SMTP in DXC doesn't work for anything without disabling certificate check. Our fix will disable the certificate check for all requests in the application though which, come to think of it, might not be acceptable for everyone. Let me know if you still want it.

**Comment by daniel-isaacs** [comment] 2020-02-21 14:38
@jtonvang What SMTP server are you using with your DXC setup -- smtp.episerver.net or smtp.sendgrid.net? If you're using the first one, does it work if you switch to the second one?

**Comment by barteksekula** [comment] 2020-03-05 08:56
@jtonvang We can try to report it as a regular product issue. So just to be clear. No emails are sent when try to use SMTP from a site under DXC? which SMTP server do you use?

**Comment by jtonvang** [comment] 2020-03-05 09:07
Sorry, forgot to answer this. We're using smtp.episerver.net, haven't tried smtp.sendgrid.net - will try when I have the chance.

**Comment by barteksekula** [comment] 2020-03-05 09:26
If you are able to reproduce that issue outside of the scope of advanced-reviews then it would be great if you could just report an issue directly in episerver partner portal. Would you be ok with it @jtonvang ? smtp.episerver.net is heavily used in hundreds of projects so there must be a reason why you needed to disable that certificate.

**Comment by daniel-isaacs** [comment] 2020-03-05 14:37
And, are you using the settings from here: https://world.episerver.com/digital-experience-cloud-service/development-considerations/configuring-the-email-server/ ? Or are you adding in the _enableSsl="true"_ property? 

If the latter, it's because the cert doesn't include the smtp.episerver.net hostname: https://www.checktls.com/TestReceiver?LEVEL=DETAIL&amp;EMAIL=smtp.episerver.net:

**Comment by jtonvang** [comment] 2020-03-06 09:47
@daniel-isaacs Good catch, we had the enableSsl attribute added. I guess that mystery is solved then 🥇

**Comment by barteksekula** [comment] 2020-03-06 12:57
So it's all good? May I close this ticket?

**Comment by jtonvang** [comment] 2020-03-06 13:01
It wasn't my ticket, so I guess @baier needs to comment whether he still has the issue.

**Comment by barteksekula** [comment] 2020-03-06 13:02
@baier all good if you use the config from https://world.episerver.com/digital-experience-cloud-service/development-considerations/configuring-the-email-server/ with enableSsl="true" ?

**Comment by jtonvang** [comment] 2020-03-06 13:03
enableSsl="true" <--- needs to be removed ;)

**Closed** 2020-03-09 12:01 UTC
Labels: help wanted

**Comment by baier** [comment] 2020-05-11 10:53
@jtonvang I'm actually a she (og norsk, i likhet med deg, antar jeg? :) ) We had to postphone adding this feature, sorry about the delayed response. Now as I'm revisiting this, I'm experiencing some issues, so I'm not able to test. But with our SMTP configuration we have the enableSsl as a requirement, so it won't be possible to remove that for us. Will test some more once I figure out how to solve the other issue.

**Comment by baier** [comment] 2020-05-11 11:52
@barteksekula Now I've have tested: When removing the enableSsl and/or setting it to false, no email is sent, and the console error is gone. We use a office365-SMTP-server. Even tried adding SpecifiedPickupDirectory (as I've tried once before on matkun's suggestion), and no email is generated. This is truely odd.
